// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WardWebsite.API.Data;

#nullable disable

namespace WardWebsite.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260330175217_AddMissingApplicationColumns")]
    partial class AddMissingApplicationColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WardWebsite.API.Models.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.ToTable("Applications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Đường Lý Thái Tổ, TP Cao Lãnh",
                            CreatedAt = new DateTime(2026, 3, 27, 17, 52, 17, 247, DateTimeKind.Utc).AddTicks(7325),
                            FullName = "Nguyễn Văn A",
                            Phone = "0912345678",
                            ServiceId = 1,
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Đường Hùng Vương, TP Cao Lãnh",
                            CreatedAt = new DateTime(2026, 3, 28, 17, 52, 17, 247, DateTimeKind.Utc).AddTicks(7332),
                            FullName = "Trần Thị B",
                            Phone = "0998765432",
                            ServiceId = 2,
                            Status = "Processing"
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Đường Cách Mạng Tháng 8, TP Cao Lãnh",
                            CreatedAt = new DateTime(2026, 3, 29, 17, 52, 17, 247, DateTimeKind.Utc).AddTicks(7333),
                            FullName = "Phạm Văn C",
                            Phone = "0934567890",
                            ServiceId = 3,
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 4,
                            Address = "321 Đường Trần Hưng Đạo, TP Cao Lãnh",
                            CreatedAt = new DateTime(2026, 3, 25, 17, 52, 17, 247, DateTimeKind.Utc).AddTicks(7335),
                            FullName = "Lê Thị D",
                            Notes = "Đã phê duyệt - Nộp hồ sơ thêm",
                            Phone = "0912341234",
                            ServiceId = 4,
                            Status = "Approved"
                        },
                        new
                        {
                            Id = 5,
                            Address = "654 Đường Phan Bội Châu, TP Cao Lãnh",
                            CreatedAt = new DateTime(2026, 3, 23, 17, 52, 17, 247, DateTimeKind.Utc).AddTicks(7336),
                            FullName = "Vũ Văn E",
                            Notes = "Thiếu giấy tờ chứng thực",
                            Phone = "0956789012",
                            ServiceId = 1,
                            Status = "Rejected"
                        });
                });

            modelBuilder.Entity("WardWebsite.API.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("WardWebsite.API.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tin Tức"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Thông Báo"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sự Kiện"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Chính Sách"
                        });
                });

            modelBuilder.Entity("WardWebsite.API.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("WardWebsite.API.Models.Media", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Media");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Type = "Image",
                            Url = "https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=400&h=300&fit=crop"
                        },
                        new
                        {
                            Id = 2,
                            Type = "Image",
                            Url = "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=400&h=300&fit=crop"
                        },
                        new
                        {
                            Id = 3,
                            Type = "Image",
                            Url = "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=400&h=300&fit=crop"
                        },
                        new
                        {
                            Id = 4,
                            Type = "Image",
                            Url = "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&h=300&fit=crop"
                        },
                        new
                        {
                            Id = 5,
                            Type = "Image",
                            Url = "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&h=300&fit=crop"
                        },
                        new
                        {
                            Id = 6,
                            Type = "Image",
                            Url = "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&h=300&fit=crop"
                        });
                });

            modelBuilder.Entity("WardWebsite.API.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Editor"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Viewer"
                        });
                });

            modelBuilder.Entity("WardWebsite.API.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Dịch vụ cấp chứng minh nhân dân",
                            Name = "Cấp CMND"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Dịch vụ cấp/thay đổi sổ hộ khẩu",
                            Name = "Cấp sổ hộ khẩu"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Dịch vụ đăng ký hôn nhân",
                            Name = "Thủ tục hôn nhân"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Dịch vụ cấp giấy khai sinh",
                            Name = "Cấp giấy khai sinh"
                        });
                });

            modelBuilder.Entity("WardWebsite.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "$2a$10$W7zrB2IPc3.lTGivsqKAL.VfLpX0K037/K5mqaQdAPmIlI35NZWPe",
                            RoleId = 3,
                            Username = "demo"
                        });
                });

            modelBuilder.Entity("WardWebsite.API.Models.Application", b =>
                {
                    b.HasOne("WardWebsite.API.Models.Service", "Service")
                        .WithMany("Applications")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("WardWebsite.API.Models.Article", b =>
                {
                    b.HasOne("WardWebsite.API.Models.Category", "Category")
                        .WithMany("Articles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WardWebsite.API.Models.Comment", b =>
                {
                    b.HasOne("WardWebsite.API.Models.Article", "Article")
                        .WithMany("Comments")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("WardWebsite.API.Models.User", b =>
                {
                    b.HasOne("WardWebsite.API.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("WardWebsite.API.Models.Article", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("WardWebsite.API.Models.Category", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("WardWebsite.API.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("WardWebsite.API.Models.Service", b =>
                {
                    b.Navigation("Applications");
                });
#pragma warning restore 612, 618
        }
    }
}
